# Generated by Django 4.0.2 on 2022-03-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_name', models.CharField(max_length=200)),
                ('Phone_number', models.IntegerField()),
                ('Email', models.EmailField(max_length=200)),
                ('Country', models.CharField(max_length=100)),
                ('Occupation', models.CharField(max_length=200)),
            ],
        ),
    ]
