# Generated by Django 4.0.2 on 2022-03-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Name_slug',
            field=models.SlugField(default='write slug', max_length=200),
        ),
    ]
