# Generated by Django 4.0.2 on 2022-03-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author_name_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='First_name',
            new_name='fast_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Last_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Occupation',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Phone_number',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Name_slug',
            new_name='slug',
        ),
    ]
