# Generated by Django 4.0.2 on 2022-03-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_country_author_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fast_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
