# Generated by Django 4.0.2 on 2022-03-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_author_user_author1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author1',
            name='user',
        ),
    ]
