# Generated by Django 4.0.2 on 2022-03-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_author1_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author1',
        ),
    ]
