# Generated by Django 4.0.2 on 2022-03-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_authorprofile_occupation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
