# Generated by Django 4.0.2 on 2022-03-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
