# Generated by Django 4.0.2 on 2022-03-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_project_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
