# Generated by Django 4.0.2 on 2022-03-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_project_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image_name',
        ),
    ]
