# Generated by Django 4.0.2 on 2022-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_project_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='post_image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
