# Generated by Django 4.0.2 on 2022-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_project_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
