# Generated by Django 4.0.2 on 2022-04-13 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_imager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imager',
            old_name='galleryimage',
            new_name='galleryimager',
        ),
        migrations.AddField(
            model_name='imager',
            name='descriptionr',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imager',
            name='sluger',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imager',
            name='titler',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
