# Generated by Django 4.0.2 on 2022-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_galleryimage_imager_galleryimager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='descriptionr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imager',
            name='galleryimager',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='imager',
            name='sluger',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
