# Generated by Django 4.0.2 on 2022-04-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_imager_descriptionr_alter_imager_galleryimager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imager',
            name='sluger',
        ),
    ]
