# Generated by Django 4.0.2 on 2022-04-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_imager_sluger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imager',
            new_name='Made',
        ),
    ]
