# Generated by Django 4.0.2 on 2022-04-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_made_sluger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='made',
            name='galleryimager',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
