# Generated by Django 4.0.2 on 2022-04-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_made_galleryimager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Made',
            new_name='Mader',
        ),
    ]
