# Generated by Django 4.0.2 on 2022-04-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_made_mader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titler', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('sluger', models.SlugField(null=True)),
                ('descriptionr', models.TextField(null=True)),
                ('galleryimager', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
