# Generated by Django 4.0.2 on 2022-04-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_meader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meader',
        ),
    ]
