# Generated by Django 4.0.2 on 2022-04-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_delete_meader'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mader',
        ),
    ]
