# Generated by Django 4.0.2 on 2022-04-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_delete_mader'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleryimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryimage', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
