# Generated by Django 4.0.2 on 2022-04-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_project_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, null=True, to='core.Galleryimage'),
        ),
    ]
