# Generated by Django 4.0.2 on 2022-05-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_galleryimage_galleryimage2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage2',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage3',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage4',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage5',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='galleryimage6',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Galleryimage',
        ),
    ]
