# Generated by Django 4.0.2 on 2022-03-19 22:53

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
