# Generated by Django 4.0.2 on 2022-03-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
