# Generated by Django 4.0.2 on 2022-03-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0003_remove_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imager',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
