# Generated by Django 4.0.2 on 2022-03-19 23:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0004_post_imager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
