# Generated by Django 4.0.2 on 2022-03-19 23:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0005_remove_post_content_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
