# Generated by Django 4.0.2 on 2022-03-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0006_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='blogcontent',
        ),
    ]
