# Generated by Django 4.0.2 on 2022-03-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0007_rename_content_post_blogcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blogcontent',
        ),
    ]
