# Generated by Django 4.0.2 on 2022-03-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0008_remove_post_blogcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='post_content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imager',
            new_name='post_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='stack.Tags'),
        ),
    ]
