# Generated by Django 4.0.2 on 2022-03-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0009_tags_rename_description_post_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
