# Generated by Django 4.0.2 on 2022-03-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0012_alter_post_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
    ]
